### ISSUE TITLE
Fail to open train.prototxt

### ISSUE THREAD

**Issue by wujiyoung** [zironycho/sublime-caffe-prototxt-syntax#1]
It worked well for solver.prototxt, but the sublime broke down when I tried to open a train.protxt or val.prototxt, any idea about it?
I was on ubuntu 16.04, sublime text 3.

**Comment by zironycho** [comment]
Could you share your train.prototxt and val.prototxt?

**Comment by edingroot** [comment]
My sublime text3 on macOS consumes a lot CPU usage after installed this package and I found that ST will freeze for a while when opening prototxt files, especially large ones.
I guess maybe there are performance issues with the package running on ST3?

**Comment by zironycho** [comment]
@wujiyoung Could you share your prototxt?
@edingroot I don't have large size prototxt, If you have one, could you share yours?

**Comment by wujiyoung** [comment]
Here is my prototxt file.
[https://raw.githubusercontent.com/shelhamer/fcn.berkeleyvision.org/master/voc-fcn32s/train.prototxt](url)

**Comment by zironycho** [comment]
@wujiyoung wow, my laptop has same issue. Thank you for reporting. I will fix it asap.

**Comment by wujiyoung** [comment]
@zironycho Thank you, and I am expecting good news from you.

**Comment by edingroot** [comment]
@zironycho I was editing prototxt like this: https://github.com/torrvision/crfasrnn/blob/master/python-scripts/TVG_CRFRNN_COCO_VOC.prototxt
Thank you, looking forward to use this great plugin!

**Comment by zironycho** [comment]
@edingroot thank you for using it.

**Comment by zironycho** [comment]
@wujiyoung @edingroot  
Thank you for issue reporting.
The new version(1.1.0) is updated  in sublime package control.
